### ISSUE TITLE
还有一个问题，就是那个key替换完以后 定位是可以了，但是添加新城市的时候就都提示失败，是还有其他地方要替换的吗，就替换了 cityBaseUrl、geoBaseUrl、com.amap.api.v2.apikey这三个地方

### ISSUE THREAD

**Issue by yishuifenglan** [xiaweizi/SimplicityWeather#6]

**Comment by xiaweizi** [comment]
你需要添加 **web API** 的服务

![image](https://user-images.githubusercontent.com/18526994/94111054-1deeb280-fe76-11ea-98ac-a680e336c00f.png)

**Comment by xiaweizi** [comment]
Android iOS分别代表不同设备，web 的代表的是接口请求
@yishuifenglan

**Comment by yishuifenglan** [comment]
就是com.amap.api.v2.apikey 用安卓的key,其他的url用web的key是吧

**Comment by xiaweizi** [comment]
> e

是的

**Comment by xiaweizi** [comment]
> 就是com.amap.api.v2.apikey 用安卓的key,其他的url用web的key是吧

是的
